steps:
  - label: "Build Wheel :python:"
    commands:
      - cd mcp_gcal
      - uv build

  - wait
  
  - label: "Publish Artifacts to Artifactory :artifactory:"
    env:
      RELEASE_BRANCH: "main"
    commands:
      - .buildkite/scripts/publish_pypi.sh mcp_gcal
